version: '3.8'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ACCOUNT_API_SERVER_PORT=8080
      - ACCOUNT_DATABASE_DSN=postgresql://postgres:postgres@postgres:5432/demo?sslmode=disable
      - ENV_CORS_ALLOWED_ORIGIN=*
    depends_on:
      - postgres
    networks:
      - account-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - account-network

volumes:
  postgres_data:

networks:
  account-network:
    driver: bridge