version: '3.8'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: account-service
    ports:
      - "8080:8080"
    environment:
      - ACCOUNT_API_SERVER_PORT=8080
      - ACCOUNT_DATABASE_DSN=postgresql://postgres:postgres@postgres:5432/demo?sslmode=disable
      - ENV_CORS_ALLOWED_ORIGIN=*
    depends_on:
      - postgres
    networks:
      - microservices-network

  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: transaction-service
    ports:
      - "8081:8081"
    environment:
      - TRANSACTION_API_SERVER_PORT=8081
      - TRANSACTION_DATABASE_DSN=postgresql://postgres:postgres@postgres:5432/demo?sslmode=disable
      - ACCOUNT_SERVICE_URL=http://account-service:8080
      - ENV_CORS_ALLOWED_ORIGIN=*
    depends_on:
      - postgres
      - account-service
    networks:
      - microservices-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge